dropout: 0.1
chara_nums: 3000
diffusion_steps: 1000
noise_schedule: 'linear'
image_size: 80
num_channels: 128
num_res_blocks: 3
batch_size: 1 #5
num_samples: 10
attention_resolutions: '40, 20, 10'
use_ddim: True
timestep_respacing: ddim25
stroke_path: './strokelist.txt'
model_path: './trained_models/ema_0.9999_336000.pt'
sty_img_path: './lan.png'
con_folder_path: './gen_text'
gen_text_stroke_path: './gen_text_stroke.txt'
total_txt_file: './wordlist.txt'
img_save_path: './result'
classifier_free: False
cont_scale: 3.0
sk_scale: 3.0
